// Generated by CoffeeScript 1.12.7
(function() {
  process.env["MONGO_CONNECTION_STRING"] = `mongodb://172.17.0.1:27017/sharelatex`;
  var Errors, HttpController, Metrics, Path, Settings, app, bodyParser, express, host, logger, port, ref;

  Metrics = require("metrics-sharelatex");

  Metrics.initialize("docstore");

  Settings = require("settings-sharelatex");

  logger = require("logger-sharelatex");

  express = require("express");

  bodyParser = require("body-parser");

  Errors = require("./app/js/Errors");

  HttpController = require("./app/js/HttpController");

  Path = require("path");

  logger.initialize("docstore");

  if ((ref = Metrics.event_loop) != null) {
    ref.monitor(logger);
  }

  app = express();

  app.use(Metrics.http.monitor(logger));

  Metrics.injectMetricsRoute(app);

  app.param('project_id', function(req, res, next, project_id) {
    if (project_id != null ? project_id.match(/^[0-9a-f]{24}$/) : void 0) {
      return next();
    } else {
      return next(new Error("invalid project id"));
    }
  });

  app.param('doc_id', function(req, res, next, doc_id) {
    if (doc_id != null ? doc_id.match(/^[0-9a-f]{24}$/) : void 0) {
      return next();
    } else {
      return next(new Error("invalid doc id"));
    }
  });

  Metrics.injectMetricsRoute(app);

  app.get('/project/:project_id/doc', HttpController.getAllDocs);

  app.get('/project/:project_id/ranges', HttpController.getAllRanges);

  app.get('/project/:project_id/doc/:doc_id', HttpController.getDoc);

  app.get('/project/:project_id/doc/:doc_id/raw', HttpController.getRawDoc);

  app.post('/project/:project_id/doc/:doc_id', bodyParser.json({
    limit: (Settings.max_doc_length + 64 * 1024) * 2
  }), HttpController.updateDoc);

  app.del('/project/:project_id/doc/:doc_id', HttpController.deleteDoc);

  app.post('/project/:project_id/archive', HttpController.archiveAllDocs);

  app.post('/project/:project_id/unarchive', HttpController.unArchiveAllDocs);

  app.post('/project/:project_id/destroy', HttpController.destroyAllDocs);

  app.get("/health_check", HttpController.healthCheck);

  app.get('/status', function(req, res) {
    return res.send('docstore is alive');
  });

  app.use(function(error, req, res, next) {
    logger.error({
      err: error,
      req: req
    }, "request errored");
    if (error instanceof Errors.NotFoundError) {
      return res.send(404);
    } else {
      return res.send(500, "Oops, something went wrong");
    }
  });

  port = Settings.internal.docstore.port;

  host = Settings.internal.docstore.host;

  // if (!module.parent) {
    app.listen(port, host, function(error) {
      if (error != null) {
        throw error;
      }
      return logger.info("Docstore starting up, listening on " + host + ":" + port);
    });
  // }

  exports.main = main
  function main(params = {}){
    const url = params.__ow_path
    const method = params.__ow_method
    const headers = params.__ow_headers
    
    const { promisify } = require('util')
    const request = require("request")
    const reqPromise = promisify(request[method]);
    return (async () => {
      let result;
      let opt={}
      opt['headers'] = headers;
      opt['url'] = `http://${host}:${port}${url}`;
      let str = params.__ow_body || '';
      if(str !== "" && Buffer.from(str, 'base64').toString('base64') === str){
        // base64
        params.__ow_body = Buffer.from(str, 'base64').toString('ascii');
      }
      opt['body'] = params.__ow_body;
      if(params.__ow_query !== ""){
        const qs = '?' + params.__ow_query;
        opt['url'] = opt['url'] + qs;
      }
      result = await reqPromise(opt);
      var response = JSON.parse(JSON.stringify(result));
      delete response.request
      return response
    })();
  }
}).call(this);

//# sourceMappingURL=app.js.map
