// Generated by CoffeeScript 1.12.7
(function() {
  var Errors, NotFoundError;

  NotFoundError = function(message) {
    var error;
    error = new Error(message);
    error.name = "NotFoundError";
    error.__proto__ = NotFoundError.prototype;
    return error;
  };

  NotFoundError.prototype.__proto__ = Error.prototype;

  module.exports = Errors = {
    NotFoundError: NotFoundError
  };

}).call(this);

//# sourceMappingURL=Errors.js.map
